#!/bin/bash
cd $HOME
if [[ ! -e project ]]; then
    mkdir project
fi
cd project
git clone https://github.com/NuanceDev/pyspeex.git   
cd pyspeex
pip install cython
make
CPPFLAGS="-I/$HOME/project/pyspeex/includes" LDFLAGS="-L/$HOME/project/pyspeex/lib" python setup.py install


